import adapter from '@sveltejs/adapter-cloudflare';
import { vitePreprocess } from '@sveltejs/kit/vite';
import { mdsvex } from 'mdsvex';
import fs from 'node:fs/promises';
import path from 'node:path';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [vitePreprocess(), mdsvex()],

  kit: {
    adapter: customAdapter(),
    alias: {
      $utils: './src/utils',
      $stores: './src/stores',
    },
  },

  extensions: ['.svelte', '.svx'],
};

function customAdapter() {
  /** @type {import('@sveltejs/kit').Adapter} */
  const _customAdpator = {
    name: 'modified-cloudlare-adapter',
    async adapt(builder) {
      // run the original Cloudflare adapter
      adapter().adapt(builder);

      // wait a moment to ensure the original adapter has finished writing files
      await new Promise((resolve) => setTimeout(resolve, 10000));

      // delete the _worker.js.map file generated by the Cloudflare adapter
      // because the source map is too large for Cloudflare
      const workerSourcemapPath = path.join(
        builder.getBuildDirectory('cloudflare'),
        '_worker.js.map'
      );
      try {
        await fs.unlink(workerSourcemapPath); // delete the file
        console.log(`[custom-cloudflare-adapter] Deleted: ${workerSourcemapPath}`);
      } catch (error) {
        if (error.code === 'ENOENT') {
          // file not found, which is fine if it wasn't generated
          console.log(
            `[custom-cloudflare-adapter] ${workerSourcemapPath} not found. Skipping deletion.`
          );
        } else {
          // other error during deletion
          console.error(
            `[custom-cloudflare-adapter] Error deleting ${workerSourcemapPath}:`,
            error
          );
        }
      }
    },
  };

  return _customAdpator;
}

export default config;
