import adapter from '@sveltejs/adapter-cloudflare';
import { vitePreprocess } from '@sveltejs/kit/vite';
import { mdsvex } from 'mdsvex';
import fs from 'node:fs/promises';
import path from 'node:path';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [vitePreprocess(), mdsvex()],

  kit: {
    adapter: customAdapter(),
    alias: {
      $utils: './src/utils',
      $stores: './src/stores',
    },
  },

  extensions: ['.svelte', '.svx'],

  vite: {
    plugins: [removeCloudflareWorkerSourcemap()],
  },
};

function customAdapter() {
  /** @type {import('@sveltejs/kit').Adapter} */
  const _customAdpator = {
    name: 'modified-cloudlare-adapter',
    async adapt(builder) {
      // run the original Cloudflare adapter
      adapter().adapt(builder);

      // wait a moment to ensure the original adapter has finished writing files
      await new Promise((resolve) => setTimeout(resolve, 10000));

      // delete the _worker.js.map file generated by the Cloudflare adapter
      // because the source map is too large for Cloudflare
      const workerSourcemapPath = path.join(
        builder.getBuildDirectory('cloudflare'),
        '_worker.js.map'
      );
      try {
        await fs.unlink(workerSourcemapPath); // delete the file
        console.log(`[custom-cloudflare-adapter] Deleted: ${workerSourcemapPath}`);
      } catch (error) {
        if (error.code === 'ENOENT') {
          // file not found, which is fine if it wasn't generated
          console.log(
            `[custom-cloudflare-adapter] ${workerSourcemapPath} not found. Skipping deletion.`
          );
        } else {
          // other error during deletion
          console.error(
            `[custom-cloudflare-adapter] Error deleting ${workerSourcemapPath}:`,
            error
          );
        }
      }
    },
  };

  return _customAdpator;
}

/**
 * A Vite plugin to remove the _worker.js.map file generated by @sveltejs/adapter-cloudflare.
 * @returns {import('vite').Plugin}
 */
function removeCloudflareWorkerSourcemap() {
  const pluginName = 'remove-cloudflare-worker-sourcemap';

  return {
    name: pluginName,
    // enforce 'post' so it runs after other build steps, including the adapter's output
    enforce: 'post',

    async writeBundle(options) {
      const workerSourcemapFileName = '_worker.js.map';
      const workerDir = path.join('.svelte-kit', 'cloudflare');

      const workerSourcemapPath = path.join(options.dir || '', workerDir, workerSourcemapFileName);

      try {
        await fs.access(workerSourcemapPath, fs.constants.F_OK); // Check if file exists
        await fs.unlink(workerSourcemapPath); // Delete the file
        console.log(`[${pluginName}] Deleted: ${workerSourcemapPath}`);
      } catch (error) {
        if (error.code === 'ENOENT') {
          // file not found, which is fine if it wasn't generated
          console.log(`[${pluginName}] ${workerSourcemapFileName} not found. Skipping deletion.`);
        } else {
          // other error during deletion
          console.error(`[${pluginName}] Error deleting ${workerSourcemapPath}:`, error);
        }
      }
    },
  };
}

export default config;
